services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build: ./crm_for_students
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./crm_for_students:/app
    env_file:
      - ./crm_for_students/.env
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data:
