# Generated by Django 5.2.7 on 2025-10-12 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_activitylogs_activitylog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'verbose_name': 'Activity Log', 'verbose_name_plural': 'Activity Logs'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='clientstage',
            options={'verbose_name': 'Client Stage', 'verbose_name_plural': 'Client Stages'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterModelTable(
            name='activitylog',
            table='activity_log',
        ),
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
        migrations.AlterModelTable(
            name='clientstage',
            table='client_stage',
        ),
        migrations.AlterModelTable(
            name='team',
            table='teams',
        ),
    ]
