# Generated by Django 5.0 on 2025-11-30 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='client',
            name='team',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='ClientStage',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
