# Generated by Django 5.0 on 2025-12-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembership',
            name='role',
            field=models.CharField(choices=[('student_captain', 'Student Captain'), ('student_member', 'Student Member'), ('client', 'Client')], max_length=50),
        ),
    ]
